title: GENCG
description: Fall 2023
remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

plugins:
  - jemoji

# Enable or disable heading anchors
heading_anchors: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Navigation links
nav:
  - Home: '/'
  - Day 1:
      - '01': '/content/day01/01/embed.html'
      - '02': '/content/day01/02/embed.html'
      - '03': '/content/day01/03/embed.html'
      - '04': '/content/day01/04/embed.html'
  - Day 2:
      - '01': '/content/day02/01/embed.html'
      - '02': '/content/day02/02/embed.html'
  - Day 3:
      - '01': '/content/day03/01/embed.html'
      - '02': '/content/day03/02/embed.html'
  - Day 4:
      - '01': '/content/day04/01/embed.html'
  
# Add more sections as needed

# Aux links for the upper right navigation
aux_links:
  "GENCG22":
    - "https://github.com/digitalideation/gencg_h2201"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
